### ISSUE TITLE
Gerar Danfe com emissor CPF

### ISSUE THREAD

**Issue by rcbull** [erpbrasil/erpbrasil.edoc.pdf#4]
Tentei emitir a Danfe para alguns XMLs cujo emissor é CPF e reportou o seguinte:

`
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    danfe = erpbrasil.edoc.pdf.ImprimirXml(file_content)
  File "/home/user/anaconda3/lib/python3.8/site-packages/erpbrasil/edoc/pdf/base.py", line 41, in __init__
    self.object_xml = objectify.fromstring(self.string_xml, parser=parser)
  File "src/lxml/objectify.pyx", line 1808, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.`

Tem algum roadmap para atualizar o repositório? Estou pensando em usar a lib xmltodict para tratar os dados da NF e checar os campos usados.

**Comment by mileo** [comment]
@rcbull obrigado pelo teste! 

Ainda não temos um Roadmap, se vc conseguir contribuir com algo. vai ser muito útil.

Temos um grupo no telegram: https://t.me/erpbrasil conforme for manda uma mensagem lá que combinamos.
